- name: Run home directory setup.
  command: /home/dgreid/HomeDir/setup.sh
  args:
      chdir: /home/dgreid

- name: Install rust compilers
  shell: curl https://sh.rustup.rs -sSf | sh

- name: Install rust-fmt
  command: rustup component add rustfmt

- name: crosvm git set push github
  command: git remote set-url --push github git@github.com:dgreid/crosvm.git
  args:
      chdir: /home/dgreid/crosvm

- name: crosvm add cros
  command: git remote add cros https://chromium.googlesource.com/chromiumos/platform/adhd
  args:
      chdir: /home/dgreid/crosvm

- name: adhd git set push github
  command: git remote set-url --push github git@github.com:dgreid/adhd.git
  args:
      chdir: /home/dgreid/adhd

- name: adhd add cros
  command: git remote add cros https://chromium.googlesource.com/chromiumos/third_party/adhd
  args:
      chdir: /home/dgreid/adhd

- name: build/install minijail
  command: make && cp *.so /lib64
  args:
      chdir: /home/dgreid/minijail

- name: dgreid is owner
  command: chown -R dgreid *.*
  args:
      chdir: /home/dgreid
